services:
  benchling-app:
    build: .
    ports:
      - "8000:5000"
    volumes:
      - type: bind
        source: .
        target: /src
    environment:
      - FLASK_DEBUG=1
      - BENCHLING_APP_LOG_LEVEL=DEBUG
      - CLIENT_ID_FILE=/run/secrets/client_id
      - APP_DEFINITION_ID_FILE=/run/secrets/app_definition_id
      - CLIENT_SECRET_FILE=/run/secrets/app_client_secret
    secrets:
      - app_client_secret
      - client_id
      - app_definition_id
    networks:
      - ngrok

  ngrok:
    image: ngrok/ngrok:latest
    command: ["start", "--config", "/etc/ngrok/ngrok.yml", "benchling-app"]  # Use the config file directly
    volumes:
      - ./ngrok.yml:/etc/ngrok/ngrok.yml  # Mount the ngrok config file
    networks:
      - ngrok

volumes:
  ngrok-config:
    external: false

secrets:
  app_client_secret:
    file: .client_secret
  client_id:
    file: .client_id
  app_definition_id:
    file: .app_definition_id
  ngrok_auth_token:
    file: .ngrok_auth_token

networks:
  ngrok:
    driver: bridge

