services:
  benchling-app:
    build: .
    ports:
      - "8000:5000"
    volumes:
      - type: bind
        source: .
        target: /src
    environment:
      - FLASK_DEBUG=1
      - BENCHLING_APP_LOG_LEVEL=DEBUG
      - CLIENT_ID=la9WwqLRyq
      - APP_DEFINITION_ID=appdef_la9X4jhuE4
      - CLIENT_SECRET_FILE=/run/secrets/app_client_secret
    secrets:
      - app_client_secret
    networks:
      - ngrok

  ngrok:
    image: ngrok/ngrok:latest
    command: ["http", "benchling-app:5000"]
    environment:
      - NGROK_AUTHTOKEN=2tDg9sKURKS8yesXCsb0BexezWP_7y6WYYhGbng9htFmAxndv
    networks:
      - ngrok

secrets:
  app_client_secret:
    file: .client_secret

networks:
  ngrok:
    driver: bridge
